name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress clean verify
      - run: mkdir staging && cp target/surefire-reports/TEST-*.xml staging
      - uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: staging